version: '3.5'
services:
  db:
    hostname: db
    image: mysql:5.7
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_DATABASE: autotest_db
        MYSQL_USER: autotest
        MYSQL_PASSWORD: autotest@2019
  web:
    hostname: web
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./:/var/www/html:cached
    ports:
      - "8000:80"
    privileged: true
