version: '3.5'
services:
  web:
    hostname: web
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./:/var/www/html:cached
    ports:
      - "8000:80"
    privileged: true
